# Generated by Django 3.1.5 on 2021-01-20 01:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import eons_data.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EonsSensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='EonsStation',
            fields=[
                ('station_code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('info', models.TextField(max_length=2500, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'EONS Station',
                'verbose_name_plural': 'EONS Stations',
                'ordering': ['station_code'],
                'permissions': (('upload_data', 'Can upload station data'), ('download_data', 'Can download station data')),
            },
        ),
        migrations.CreateModel(
            name='EonsCsv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_date', models.DateTimeField(auto_now_add=True)),
                ('file_name', models.FileField(upload_to=eons_data.models.content_file_name)),
                ('activated', models.BooleanField(default=False)),
                ('station_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='eons_data.eonsstation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'EONS CSV',
                'verbose_name_plural': 'EONS CSVs',
            },
        ),
        migrations.CreateModel(
            name='EonsBaseData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utc_datetime', models.DateTimeField()),
                ('local_datetime', models.DateTimeField(null=True)),
                ('temperature', models.DecimalField(decimal_places=1, max_digits=4)),
                ('battery_voltage', models.DecimalField(decimal_places=2, max_digits=4)),
                ('surf_brightness', models.FloatField()),
                ('init_subs', models.FloatField()),
                ('sky_counts', models.IntegerField(null=True)),
                ('sky_brightness_discard', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('sky_led_counts', models.IntegerField(null=True)),
                ('moon_phase_deg', models.DecimalField(decimal_places=1, max_digits=6)),
                ('moon_elev_deg', models.DecimalField(decimal_places=3, default=0.0, max_digits=6)),
                ('moon_illum_percent', models.DecimalField(decimal_places=1, max_digits=4)),
                ('sun_elev_deg', models.DecimalField(decimal_places=3, max_digits=6)),
                ('station', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='eons_data.eonsstation')),
            ],
            options={
                'verbose_name': 'EONS Datum',
                'verbose_name_plural': 'EONS Data',
                'unique_together': {('station', 'utc_datetime')},
            },
        ),
    ]
