# Generated by Django 3.1.5 on 2021-01-23 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eons_data', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eonssensor',
            name='id',
        ),
        migrations.AddField(
            model_name='eonssensor',
            name='is_snow_sensor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='eonssensor',
            name='sensor_id',
            field=models.CharField(default='asdf', max_length=10, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eonssensor',
            name='station_code',
            field=models.ForeignKey(default='sensor1', on_delete=django.db.models.deletion.PROTECT, to='eons_data.eonsstation'),
            preserve_default=False,
        ),
    ]
