# Generated by Django 3.1.1 on 2020-09-27 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eons_data', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eonssite',
            name='id',
        ),
        migrations.AlterField(
            model_name='eonssite',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eonssite',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eonssite',
            name='site_code',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
