# Generated by Django 3.1.1 on 2020-09-27 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eons_data', '0002_auto_20200927_2131'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eonssite',
            options={'ordering': ['site_code'], 'permissions': (('upload_data', 'Can upload site data'), ('download_data', 'Can download site data'))},
        ),
    ]
