# Generated by Django 3.1.5 on 2021-01-23 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eons_data', '0002_auto_20210123_2105'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eonssensor',
            options={'verbose_name': ('EONS Sensor',), 'verbose_name_plural': 'EONS Sensors'},
        ),
        migrations.AlterField(
            model_name='eonssensor',
            name='station_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sensors', to='eons_data.eonsstation'),
        ),
    ]
