# Generated by Django 3.1.1 on 2020-09-27 21:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eons_data', '0003_auto_20200927_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='eonssite',
            name='users',
            field=models.ManyToManyField(related_name='users', to=settings.AUTH_USER_MODEL),
        ),
    ]
