# Generated by Django 3.1.5 on 2021-01-23 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eons_data', '0003_auto_20210123_2112'),
    ]

    operations = [
        migrations.AddField(
            model_name='eonsbasedata',
            name='sensor_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='eons_data.eonssensor'),
        ),
        migrations.AddField(
            model_name='eonscsv',
            name='sensor_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='eons_data.eonssensor'),
        ),
        migrations.AlterField(
            model_name='eonscsv',
            name='station_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='eons_data.eonsstation'),
        ),
    ]
