# Generated by Django 3.1.1 on 2020-10-05 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eons_data', '0004_eonssite_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eonssite',
            name='users',
        ),
        migrations.AddField(
            model_name='eonssite',
            name='users',
            field=models.TextField(blank=True, null=True),
        ),
    ]
