# Generated by Django 3.1.5 on 2021-01-23 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eons_data', '0005_auto_20210123_2217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eonsbasedata',
            name='surf_brightness',
        ),
        migrations.AddField(
            model_name='eonsbasedata',
            name='sky_brightness',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=10),
            preserve_default=False,
        ),
    ]
