# Generated by Django 3.1.5 on 2021-01-23 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eons_data', '0006_auto_20210123_2219'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eonsbasedata',
            options={'verbose_name': 'EONS Raw Datum', 'verbose_name_plural': 'EONS Raw Data'},
        ),
        migrations.AlterUniqueTogether(
            name='eonsbasedata',
            unique_together={('sensor_id', 'utc_datetime')},
        ),
    ]
