# Generated by Django 3.1.1 on 2020-10-05 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eons_data', '0006_auto_20201005_0302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eonssite',
            name='users',
        ),
    ]
