# Generated by Django 3.1.5 on 2021-01-23 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eons_data', '0007_auto_20210123_2220'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eonscsv',
            old_name='activated',
            new_name='converted_to_raw_data',
        ),
    ]
