# Generated by Django 3.1.2 on 2021-01-17 20:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eons_data', '0007_remove_eonssite_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='EonsCsv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.FileField(upload_to='eons_csvs/')),
                ('uploaded_date', models.DateTimeField(auto_now_add=True)),
                ('site_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='eons_data.eonssite')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
