# Generated by Django 3.1.2 on 2021-01-17 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eons_data', '0008_eonscsv'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eonscsv',
            options={'verbose_name': 'EONS CSV', 'verbose_name_plural': 'EONS CSVs'},
        ),
        migrations.AddField(
            model_name='eonscsv',
            name='activated',
            field=models.BooleanField(default=False),
        ),
    ]
