# Generated by Django 3.1.2 on 2021-01-17 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eons_data', '0009_auto_20210117_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eonscsv',
            name='file_name',
            field=models.FileField(upload_to='eons_csvs/<django.db.models.fields.related.ForeignKey>/'),
        ),
    ]
