# Generated by Django 3.1.2 on 2021-01-17 21:26

from django.db import migrations, models
import eons_data.models


class Migration(migrations.Migration):

    dependencies = [
        ('eons_data', '0012_auto_20210117_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eonscsv',
            name='file_name',
            field=models.FileField(upload_to=eons_data.models.content_file_name),
        ),
    ]
