# Generated by Django 3.1.5 on 2021-01-18 00:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eons_data', '0013_auto_20210117_2126'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eonssite',
            options={'ordering': ['site_code'], 'permissions': (('upload_data', 'Can upload site data'), ('download_data', 'Can download site data')), 'verbose_name': 'EONS Site', 'verbose_name_plural': 'EONS Sites'},
        ),
        migrations.CreateModel(
            name='EonsBaseData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utc_datetime', models.DateTimeField()),
                ('temperature', models.FloatField()),
                ('battery_voltage', models.FloatField()),
                ('surf_brightness', models.FloatField()),
                ('init_subs', models.FloatField()),
                ('moon_phase_deg', models.FloatField()),
                ('moon_elev_def', models.FloatField()),
                ('moon_illum_percent', models.FloatField()),
                ('site_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='eons_data.eonssite')),
            ],
        ),
    ]
