# Generated by Django 3.1.5 on 2021-01-18 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eons_data', '0015_auto_20210118_0202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eonsbasedata',
            name='moon_elev_def',
        ),
        migrations.AddField(
            model_name='eonsbasedata',
            name='moon_elev_deg',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='eonsbasedata',
            name='sky_brightness_discard',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='eonsbasedata',
            name='sky_counts',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='eonsbasedata',
            name='sky_led_counts',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='eonsbasedata',
            name='battery_voltage',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='eonsbasedata',
            name='moon_illum_percent',
            field=models.DecimalField(decimal_places=1, max_digits=4),
        ),
        migrations.AlterField(
            model_name='eonsbasedata',
            name='moon_phase_deg',
            field=models.DecimalField(decimal_places=1, max_digits=6),
        ),
        migrations.AlterField(
            model_name='eonsbasedata',
            name='temperature',
            field=models.DecimalField(decimal_places=1, max_digits=4),
        ),
    ]
