# Generated by Django 3.1.5 on 2021-01-18 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eons_data', '0016_auto_20210118_2018'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eonsbasedata',
            old_name='site_code',
            new_name='site',
        ),
    ]
